name: Update Playlist

on:
  push:
    paths:
      - 'raw_files/*'  # This triggers the workflow when files in the 'raw_files' folder are changed
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  update-playlist:
    runs-on: ubuntu-latest  # Uses Ubuntu environment to run the script
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Install Python

    - name: Install dependencies
      run: |
        pip install requests  # Install required Python library

    - name: Run the update playlist script
      run: |
        python update_playlist.py  # Run the Python script
